#!/usr/bin/env python3
"""Download the docs site fonts from Google Fonts for self-hosting.

Zensical otherwise loads webfonts from the Google Fonts CDN at runtime (see the
`{% block fonts %}` in its `base.html`). To avoid the third-party request we set
`theme.font: false` in `mkdocs.yml` and self-host instead.

This script fetches the exact font families, weights and styles that Zensical
would normally request, downloads the `woff2` files into `docs/fonts/`, and
generates `docs/stylesheets/fonts.css` with `@font-face` rules pointing at the
local files plus the `--md-text-font` / `--md-code-font` variables the theme
relies on. Both outputs are gitignored and regenerated on every build.

Run it before `zensical build`:

    python scripts/fetch-fonts.py && zensical build --strict

Uses only the standard library, so no extra dependencies are required.
"""

from __future__ import annotations

import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

# Families, weights and styles must mirror what Zensical requests in base.html:
#   text -> 300,300i,400,400i,500,500i,700,700i
#   code -> 400,400i,700,700i
FONTS = {
    "Inter": "ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700",
    "JetBrains Mono": "ital,wght@0,400;0,700;1,400;1,700",
}
TEXT_FONT = "Inter"
CODE_FONT = "JetBrains Mono"

# A modern browser UA is required for Google Fonts to serve woff2.
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "docs" / "fonts"
CSS_OUT = ROOT / "docs" / "stylesheets" / "fonts.css"

FACE_RE = re.compile(
    r"(?:/\*\s*(?P<subset>[^*]+?)\s*\*/\s*)?"
    r"@font-face\s*\{(?P<body>[^}]*)\}",
    re.DOTALL,
)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request) as response:
        return response.read()


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def find(pattern: str, text: str, default: str = "") -> str:
    match = re.search(pattern, text)
    return match.group(1) if match else default


def main() -> int:
    query = "&".join(
        f"family={family.replace(' ', '+')}:{axes}"
        for family, axes in FONTS.items()
    )
    url = f"https://fonts.googleapis.com/css2?{query}&display=fallback"

    try:
        css = fetch(url).decode("utf-8")
    except urllib.error.URLError as error:
        print(f"error: failed to fetch Google Fonts CSS: {error}", file=sys.stderr)
        return 1

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    for stale in FONT_DIR.glob("*.woff2"):
        stale.unlink()

    faces: list[str] = []
    downloaded = 0

    for match in FACE_RE.finditer(css):
        body = match.group("body")
        subset = match.group("subset") or "default"
        family = find(r"font-family:\s*'([^']+)'", body)
        style = find(r"font-style:\s*(\w+)", body, "normal")
        weight = find(r"font-weight:\s*(\d+)", body, "400")
        src = find(r"url\((https://[^)]+\.woff2)\)", body)
        if not (family and src):
            continue

        name = f"{slug(family)}-{slug(subset)}-{weight}-{style}.woff2"
        try:
            (FONT_DIR / name).write_bytes(fetch(src))
        except urllib.error.URLError as error:
            print(f"error: failed to download {src}: {error}", file=sys.stderr)
            return 1
        downloaded += 1

        local_body = body.replace(src, f"../fonts/{name}").strip()
        local_body = re.sub(r"\s*\n\s*", "\n  ", local_body)
        faces.append(f"/* {subset} */\n@font-face {{\n  {local_body}\n}}")

    if not faces:
        print("error: no @font-face rules parsed from Google Fonts CSS", file=sys.stderr)
        return 1

    header = (
        "/* Generated by scripts/fetch-fonts.py - do not edit. */\n"
        "/* Self-hosted webfonts; regenerate with `python scripts/fetch-fonts.py`. */\n\n"
        ":root {\n"
        f'  --md-text-font: "{TEXT_FONT}";\n'
        f'  --md-code-font: "{CODE_FONT}";\n'
        "}\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(faces) + "\n", encoding="utf-8")

    print(f"Downloaded {downloaded} font files to {FONT_DIR.relative_to(ROOT)}")
    print(f"Wrote {CSS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
